name: Build UI
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndDeployUI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Deps
        run: cd frontend && npm ci
      - name: Build Application
        run: cd frontend && npm run build
      - name: List Directory
        run: ls -l frontend