name: Build Go
on: [push]

jobs:
  BuildFunctions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: ["leaderboard", "players", "seasons"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Build Function
        run: echo ${{matrix.function}}