name: Build Go
on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/functions.yml
      - functions/**
      - internal/**
  

permissions:
  id-token: write
  contents: read

jobs:
  BuildLambdas:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: ["leaderboard", "players", "seasons", "venues", "tournaments"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: go env
      - run: mkdir .build
      - name: Build Function
        run: |
          GOOS=linux go build -o ./.build/${{matrix.function}} ./functions/${{matrix.function}}/*.go
      - name: Zip Artifact
        run: |
          zip -j ./.build/${{matrix.function}}_handler.zip ./.build/${{matrix.function}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::847870459364:role/GithubActionOIDC
      - name: Upload to S3
        run: |
          aws s3 cp ./.build/${{matrix.function}}_handler.zip s3://ppc-lambda-functions/${{matrix.function}}_handler.zip
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name ${{matrix.function}}_handler --s3-bucket ppc-lambda-functions --s3-key ${{matrix.function}}_handler.zip
      