name: Build Go
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  CheckCallerIdentity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function: ["leaderboard", "players", "seasons"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: mkdir .build
      - name: Build Function
        run: |
          GOOS=linux go build -o ./.build/${{matrix.function}}/${{matrix.function}} ./functions/${{matrix.function}}/*.go
      - run: ls -l .build
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     aws-region: us-east-1
      #     role-to-assume: arn:aws:iam::847870459364:role/GithubActionOIDC