name: Build Go
on: [push]

jobs:
  BuildFunctions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ["leaderboard", "players", "seasons"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build Function
        run: echo ${{matrix.function}}
